{% set name = "pytest-integration" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_integration-{{ version }}.tar.gz
  sha256: b00988a5de8a6826af82d4c7a3485b43fbf32c11235e9f4a8b7225eef5fbcf65

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show pytest-integration
    # check that pytest knows about us
    - pytest --trace-config | grep pytest_integration  # [unix]

about:
  home: https://github.com/jbwdevries/pytest-integration
  summary: Organizing pytests by integration or not
  license: MIT
  license_file: LICENSE
  description: |
    Plugin for pytest to mark tests as integration or slow integration.

    Integration tests are run after normal tests (unit tests) and slow
    integration tests are run after (quick) integration tests.

    If a unit test fails, (quick) integration and slow integration tests
    are not run.

    If a (quick) integration tests fails, slow integration tests are not run.

    If you have also installed pytest-cov, then code coverage is disabled for
    all integration tests, since unit tests are supposed to cover all the code.

extra:
  recipe-maintainers:
    - duncanmmacleod
